/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import cumulative.poetry.variousPoets.OnlyPoet;
import cumulative.poetry.variousPoets.SingerPoet;

public class PoetTest {
	@Test
	public void shouldSaySomething() {
		PoetI poet = new OnlyPoet();
		assertFalse("Poet should say something, but said nothing", poet.recite(1).isEmpty());
	}

	@Test
	public void fullStory() {
		PoetI poet = new OnlyPoet();
		assertFalse("Poet should say something, but said nothing", poet.recite(12).isEmpty());
	}
	
	@Test
	public void echoVsNormal() {
		OnlyPoet oPoet = new OnlyPoet();
		SingerPoet sPoet = new SingerPoet();
		assertTrue("Echo is twice normal",oPoet.recite(5).split("\n").length*2-1==sPoet.recite(5).split("\n").length);
	}
}
