/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

import static org.junit.Assert.assertFalse;

import org.junit.Test;

import cumulative.poetry.implementation.OnlyPoet;

public class PoetTest {
	@Test
	public void shouldSaySomething() {
		PoetI poet = new OnlyPoet();
		assertFalse("Poet should say something, but said nothing", poet.recite(1).isEmpty());
	}

	@Test
	public void fullStory() {
		PoetI poet = new OnlyPoet();
		assertFalse("Poet should say something, but said nothing", poet.recite(12).isEmpty());
	}
}
