/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cumulative.poetry;

public class Poet {
	static String[] poetry = { "the horse and the hound and the horn that belonged to\n\t",
			"the farmer sowing his corn that kept\n\t", "the rooster that crowed in the morn that woke\n\t",
			"the priest all shaven and shorn that married\n\t", "the man all tattered and torn that kissed\n\t",
			"the maiden all forlorn that milked\n\t", "that cow with the crumpled horn that tossed\n\t", "the dog that worried\n\t",
			"the cat that killed\n\t", "the rat that ate\n\t", "the malth that lay in\n\t", "the house that Jack built.\n\t" };
	static String prefix = "This is ";

	public String recite(int day) {
		StringBuilder poemStory = new StringBuilder();
		poemStory.append(prefix);
		for(int i=(12-day);i<poetry.length;i++) {
			poemStory.append(poetry[i]);
		}
		return poemStory.toString();
	}
	
	public String echoRecite(int day) {
		StringBuilder poemStory = new StringBuilder();
		poemStory.append(prefix);
		for(int i=(12-day);i<poetry.length;i++) {
			poemStory.append(poetry[i]);
			poemStory.append(poetry[i]);
		}
		return poemStory.toString();
	}
}
